services:
  mongo:
    container_name: mongo-gestor-tarefas
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-gestor-tarefas-volume:/data/db
    restart: always


  api:
    container_name: api-gestor-tarefas
    build: ./
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    volumes:
      - ./:/api


volumes:
  mongodb-gestor-tarefas-volume: