services:
  mongo:
    container_name: mongo-gestor-tarefas
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-gestor-tarefas-volume:/data/db
    restart: always


  api:
    container_name: api-gestor-tarefas
    build: ./
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    volumes:
      - ./:/api

  frontend:
    container_name: frotend-gestor
    build: ./frontend
    depends_on:
      - api
    volumes:
      - front-volume:/var/www/html
    
  nginx:
    container_name: nginx-gestor
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - front-volume:/var/www/html 
    depends_on:
      - mongo
      - api
      - frontend
volumes:
  mongodb-gestor-tarefas-volume:
  front-volume: